name: 🍜 Build/publish base runners

on:
  push:
    paths:
      - 'images/*.Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      base_files: ${{ steps.filter.outputs.base_files }}
      torch_files: ${{ steps.filter.outputs.torch_files }}
      tf_files: ${{ steps.filter.outputs.tf_files }}
      tvm_files: ${{ steps.filter.outputs.tvm_files }}
      opencv_files: ${{ steps.filter.outputs.opencv_files }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: 'json'
          base: 'feat_fix_jetson~1'
          filters: |
            base:
              - 'images/rootless-ubuntu-*-base.Dockerfile'
            torch:
              - 'images/rootless-ubuntu-*-torch.Dockerfile'
            tf:
              - 'images/rootless-ubuntu-*-tf.Dockerfile'
            tvm:
              - 'images/rootless-ubuntu-*-tvm.Dockerfile'
            opencv:
              - 'images/rootless-ubuntu-*-opencv.Dockerfile'

  process-dockerfiles:
    needs: get-changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [base, torch, tf, tvm, opencv]
    outputs:
      processed_files: ${{ steps.process.outputs.processed_files }}
    steps:
      - name: Process Changed Files
        id: process
        env:
          ALL_OUTPUTS: ${{ toJson(needs.get-changed-files.outputs) }}
          CATEGORY: ${{ matrix.category }}
        run: |
          FILES=$(echo "$ALL_OUTPUTS" | jq -r ".\"${CATEGORY}_files\"")

          if [ "$FILES" = "[]" ]; then
            echo "processed_files=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Convert JSON array to Bash array
          FILES_ARRAY=($(echo "$FILES" | jq -r '.[]'))

          NEW_FILE_NAMES=()
          for FILE_PATH in "${FILES_ARRAY[@]}"; do
            NEW_NAME=$(basename "$FILE_PATH" .Dockerfile | sed 's/^images\///')
            NEW_FILE_NAMES+=("\"$NEW_NAME\"")
          done

          JSON_OUTPUT=$(printf "[%s]" "$(IFS=,; echo "${NEW_FILE_NAMES[*]}")")
          echo "processed_files=$JSON_OUTPUT" >> "$GITHUB_OUTPUT"


  build-dockerfiles:
    needs: process-dockerfiles
    strategy:
      matrix:
        category: [base, torch, tf, tvm, opencv]
    if: ${{ needs.process-dockerfiles.outputs.processed_files != '[]' }}
    uses: ./.github/workflows/build-latest.yml
    secrets: inherit
    with:
      runner: '["base", "dind", "2204"]'
      runner-archs: ${{ matrix.category == 'base' && '["amd64", "arm64", "arm"]' || '["amd64", "arm64"]' }}
      dockerfiles: ${{ needs.process-dockerfiles.outputs.processed_files }}

